name: Run API Pytest testcases and Generate Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GOREST_TOKEN: ${{ secrets.GOREST_TOKEN }}

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 4. Run all pytest testcases with Allure results
      - name: Run Pytest
        run: |
          pytest -v --alluredir=allure-results

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.26.0/allure-2.26.0.tgz
          tar -xzf allure-2.26.0.tgz
          sudo mv allure-2.26.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report


      # 6. Upload Allure report as artifact
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report